default_agent: my_agent
agents:
  my_agent:
    name: my_agent
    entrypoint: my_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: .
    aws:
      execution_role: arn:aws:iam::448049797912:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e72c1a7c7a
      execution_role_auto_create: false
      account: '448049797912'
      region: us-east-1
      ecr_repository: 448049797912.dkr.ecr.us-east-1.amazonaws.com/deluxe-sdlc
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: my_agent-0BLwDgF9uK
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:448049797912:runtime/my_agent-0BLwDgF9uK
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::448049797912:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-448049797912-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: my_agent_mem-iCSv334U5y
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:448049797912:memory/my_agent_mem-iCSv334U5y
      memory_name: my_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  analyst_agent:
    name: analyst_agent
    entrypoint: analyst_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: .bedrock_agentcore/analyst_agent
    aws:
      execution_role: arn:aws:iam::448049797912:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e72c1a7c7a
      execution_role_auto_create: false
      account: '448049797912'
      region: us-east-1
      ecr_repository: 448049797912.dkr.ecr.us-east-1.amazonaws.com/deluxe-sdlc
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: Analyst_agent-kCoE8v38c0
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:448049797912:runtime/Analyst_agent-kCoE8v38c0
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-analyst_agent-builder
      execution_role: arn:aws:iam::448049797912:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-448049797912-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: Test-DGwqpP7Rvj
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:448049797912:memory/Test-DGwqpP7Rvj
      memory_name: Test
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
